import { Command } from "commander";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { generateSecretKey, getPublicKey, nip19 } from "nostr-tools";
import { bytesToHex } from "@noble/hashes/utils";
import { banner, success, error, warn, info, createSpinner } from "../utils/display.js";

function checkNodeVersion(): boolean {
  const major = parseInt(process.versions.node.split(".")[0], 10);
  return major >= 22;
}

function findWorkspace(): string | null {
  const homeDir = join(homedir(), ".openclaw");
  if (existsSync(homeDir)) return homeDir;

  const localDir = join(process.cwd(), ".openclaw");
  if (existsSync(localDir)) return localDir;

  return null;
}

export const initCommand = new Command("init")
  .description("Initialize Hydraa in your OpenClaw workspace")
  .action(async () => {
    banner();

    // Check Node version
    if (!checkNodeVersion()) {
      error(`Node 22+ is required. You have Node ${process.versions.node}`);
      process.exit(1);
    }
    success("Node version OK");

    // Find or prompt for workspace
    let workspace = findWorkspace();
    if (!workspace) {
      warn("No OpenClaw workspace found (~/.openclaw or ./.openclaw)");
      info("Creating workspace at ~/.openclaw");
      workspace = join(homedir(), ".openclaw");
      mkdirSync(workspace, { recursive: true });
    }
    success(`Workspace: ${workspace}`);

    // Generate Nostr keypair
    const spinner = createSpinner("Generating Nostr keypair...");
    spinner.start();

    const sk = generateSecretKey();
    const pk = getPublicKey(sk);
    const npub = nip19.npubEncode(pk);
    const nsec = nip19.nsecEncode(sk);

    spinner.succeed("Nostr keypair generated");

    console.log();
    info(`Your agent's public identity:`);
    console.log(`  npub: ${npub}`);
    console.log();
    warn("Save your nsec (secret key) securely. It will NOT be shown again.");
    console.log(`  nsec: ${nsec}`);
    console.log();

    // Create config directory and template
    const skillDir = join(workspace, "skills", "hydraa");
    mkdirSync(skillDir, { recursive: true });

    const configPath = join(skillDir, "config.yaml");
    if (!existsSync(configPath)) {
      const configTemplate = `# Hydraa Configuration
# Generated by hydraa init

nostr:
  # Your agent's Nostr secret key (hex format)
  secret_key: "${bytesToHex(sk)}"
  # Relays to connect to
  relays:
    - "wss://relay.damus.io"
    - "wss://nos.lol"
    - "wss://relay.nostr.band"

akash:
  # Wallet mnemonic for AKT payments (set via HYDRAA_AKT_MNEMONIC env var)
  # mnemonic: ""
  # RPC endpoint
  rpc: "https://rpc.akashnet.net:443"
  # Chain ID
  chain_id: "akashnet-2"

compute:
  # Default provider: akash | self-hosted
  provider: "akash"
  # Container resources
  cpu: 0.5
  memory: "512Mi"
  storage: "1Gi"

heartbeat:
  # Check interval in minutes
  cheap_interval: 5
  # Daily summary hour (UTC)
  summary_hour: 9
`;
      writeFileSync(configPath, configTemplate, "utf-8");
      success(`Config created: ${configPath}`);
    } else {
      warn(`Config already exists: ${configPath}`);
    }

    // Check for AKT wallet
    const aktMnemonic = process.env["HYDRAA_AKT_MNEMONIC"];
    if (!aktMnemonic) {
      warn("No AKT wallet mnemonic found (HYDRAA_AKT_MNEMONIC)");
      info("You'll need AKT tokens to deploy. See: hydraa fund");
    } else {
      success("AKT wallet mnemonic found");
    }

    // Next steps
    console.log();
    console.log("  Next steps:");
    console.log("  ─────────────────────────────────────────────");
    info("1. Fund your AKT wallet:          hydraa fund");
    info("2. Deploy to Akash:               hydraa deploy");
    info("3. Check status:                  hydraa status");
    info("4. Chat with your agent:          hydraa chat");
    console.log();
  });
