import { Command } from "commander";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { generateSecretKey, getPublicKey, nip19 } from "nostr-tools";
import { bytesToHex } from "@noble/hashes/utils";
import { DirectSecp256k1HdWallet } from "@cosmjs/proto-signing";
import { banner, success, error, warn, info, createSpinner } from "../utils/display.js";

/** Generate a 24-word BIP39 mnemonic using cosmjs */
async function generateMnemonic(): Promise<string> {
  // DirectSecp256k1HdWallet.generate creates a wallet with a random mnemonic
  const wallet = await DirectSecp256k1HdWallet.generate(24, { prefix: "akash" });
  return wallet.mnemonic;
}

function checkNodeVersion(): boolean {
  const major = parseInt(process.versions.node.split(".")[0], 10);
  return major >= 22;
}

function findWorkspace(): string | null {
  const homeDir = join(homedir(), ".openclaw");
  if (existsSync(homeDir)) return homeDir;

  const localDir = join(process.cwd(), ".openclaw");
  if (existsSync(localDir)) return localDir;

  return null;
}

export const initCommand = new Command("init")
  .description("Initialize Hydraa in your OpenClaw workspace")
  .action(async () => {
    banner();

    // Check Node version
    if (!checkNodeVersion()) {
      error(`Node 22+ is required. You have Node ${process.versions.node}`);
      process.exit(1);
    }
    success("Node version OK");

    // Find or prompt for workspace
    let workspace = findWorkspace();
    if (!workspace) {
      warn("No OpenClaw workspace found (~/.openclaw or ./.openclaw)");
      info("Creating workspace at ~/.openclaw");
      workspace = join(homedir(), ".openclaw");
      mkdirSync(workspace, { recursive: true });
    }
    success(`Workspace: ${workspace}`);

    // Generate Nostr keypair
    const nostrSpinner = createSpinner("Generating Nostr keypair...");
    nostrSpinner.start();

    const sk = generateSecretKey();
    const pk = getPublicKey(sk);
    const npub = nip19.npubEncode(pk);
    const nsec = nip19.nsecEncode(sk);

    nostrSpinner.succeed("Nostr keypair generated");

    console.log();
    info("Your agent's Nostr identity:");
    console.log(`  npub: ${npub}`);
    console.log();
    warn("Save your nsec (secret key) securely. It will NOT be shown again.");
    console.log(`  nsec: ${nsec}`);
    console.log();

    // Generate AKT wallet
    const aktSpinner = createSpinner("Generating AKT wallet...");
    aktSpinner.start();

    const mnemonic = await generateMnemonic();
    const wallet = await DirectSecp256k1HdWallet.fromMnemonic(mnemonic, {
      prefix: "akash",
    });
    const [account] = await wallet.getAccounts();
    const walletAddress = account.address;

    aktSpinner.succeed("AKT wallet generated");

    console.log();
    warn("Save your AKT wallet mnemonic securely. It will NOT be shown again.");
    console.log();
    console.log(`  Mnemonic: ${mnemonic}`);
    console.log();
    console.log(`  Wallet Address: ${walletAddress}`);
    console.log();
    info(`To deploy, send ~$5 worth of AKT tokens to:`);
    console.log(`  ${walletAddress}`);
    console.log();
    info("I'll check the balance periodically and let you know when it's funded!");
    console.log();

    // Create config directory and template
    const skillDir = join(workspace, "skills", "hydraa");
    mkdirSync(skillDir, { recursive: true });

    const configPath = join(skillDir, "config.yaml");
    if (!existsSync(configPath)) {
      const configTemplate = `# Hydraa Configuration
# Generated by hydraa init

nostr:
  # Your agent's Nostr secret key (hex format)
  secret_key: "${bytesToHex(sk)}"
  # Relays to connect to
  relays:
    - "wss://relay.damus.io"
    - "wss://nos.lol"
    - "wss://relay.nostr.band"

akash:
  # Wallet mnemonic for AKT payments
  mnemonic: "${mnemonic}"
  # Wallet address (derived from mnemonic)
  address: "${walletAddress}"
  # RPC endpoint
  rpc: "https://rpc.akashnet.net:443"
  # Chain ID
  chain_id: "akashnet-2"

compute:
  # Default provider: akash | self-hosted
  provider: "akash"
  # Container resources
  cpu: 0.5
  memory: "512Mi"
  storage: "1Gi"

heartbeat:
  # Check interval in minutes
  cheap_interval: 5
  # Daily summary hour (UTC)
  summary_hour: 9
`;
      writeFileSync(configPath, configTemplate, "utf-8");
      success(`Config created: ${configPath}`);
    } else {
      warn(`Config already exists: ${configPath}`);
    }

    // Next steps
    console.log();
    console.log("  Next steps:");
    console.log("  ─────────────────────────────────────────────");
    info(`1. Fund your wallet:              Send AKT to ${walletAddress}`);
    info("2. Check balance:                 hydraa fund");
    info("3. Deploy to Akash:               hydraa deploy");
    info("4. Check status:                  hydraa status");
    info("5. Chat with your agent:          hydraa chat");
    console.log();
  });
