/**
 * Dockerfile generator for OpenClaw agent containers.
 */

interface DockerfileConfig {
  /** Node.js major version (e.g. "22") */
  nodeVersion: string;
  /** List of OpenClaw skills to install */
  skills: string[];
  /** Whether everclaw (Morpheus integration) is included */
  hasEverclaw: boolean;
}

/**
 * Generate a Dockerfile for an OpenClaw agent container.
 * Uses Alpine for minimal image size, installs pnpm, copies workspace,
 * and sets up the entrypoint.
 */
export function generateDockerfile(config: DockerfileConfig): string {
  const { nodeVersion, skills, hasEverclaw } = config;

  const skillInstallLines = skills
    .map((skill) => `RUN pnpm add ${skill}`)
    .join('\n');

  const everclawComment = hasEverclaw
    ? '\n# Everclaw detected — Morpheus inference routes will be available'
    : '';

  return `# Generated by Hydraa
FROM node:${nodeVersion}-alpine

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Create workspace directory
WORKDIR /app/workspace

# Copy dependency files first for layer caching
COPY package.json pnpm-lock.yaml* ./

# Install dependencies
RUN pnpm install --frozen-lockfile --prod 2>/dev/null || pnpm install --prod

# Copy workspace files
COPY . .

# Install skills
${skillInstallLines || '# No additional skills to install'}
${everclawComment}

# Create persistent data directory
RUN mkdir -p /data

# Set environment
ENV NODE_ENV=production
ENV OPENCLAW_WORKSPACE=/app/workspace
ENV OPENCLAW_DATA_DIR=/data

# Entrypoint — start the OpenClaw gateway
ENTRYPOINT ["node", "node_modules/.bin/openclaw", "gateway"]
`;
}
